<?php

return [
    'mode'                     => 'utf-8',
    'format'                   => 'A4',
    'default_font_size'        => '12',
    'default_font'             => 'hind',
    'margin_left'              => 8,
    'margin_right'             => 8,
    'margin_top'               => 8,
    'margin_bottom'            => 8,
    'margin_header'            => 0,
    'margin_footer'            => 0,
    'orientation'              => 'P',
    'title'                    => 'Sanskar Shivir PDF',
    'subject'                  => '',
    'author'                   => 'Punyodaya Bharat',
    'watermark'                => '',
    'show_watermark'           => false,
    'show_watermark_image'     => false,
    'watermark_font'           => 'sans-serif',
    'display_mode'             => 'fullpage',
    'watermark_text_alpha'     => 0.1,
    'watermark_image_path'     => '',
    'watermark_image_alpha'    => 0.2,
    'watermark_image_size'     => 'D',
    'watermark_image_position' => 'P',
    'custom_font_dir'          => public_path('fonts/'),
    'custom_font_data'         => [
        'hind' => [
            'R'          => 'Hind-Regular.ttf',
            'B'          => 'Hind-Bold.ttf',
            'useOTL'     => 0xFF,
            'useKashida' => 79,
        ]
    ],
    'auto_language_detection'  => true,
    'temp_dir'                 => storage_path('app'),
    'pdfa'                     => false,
    'pdfaauto'                 => false,
    'use_active_forms'         => false,
];
